# Generated by Django 6.0.1 on 2026-01-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqladi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transactioncategory', verbose_name='Kategoriya'),
        ),
    ]
