# Generated by Django 6.0.1 on 2026-01-18 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_assetcategory_asset_supplycategory_supply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('transfer', "Bank o'tkazmasi"), ('online', "Online to'lov")], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Chek fayli (PDF)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_notes',
            field=models.TextField(blank=True, verbose_name='Chek izohi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_verified',
            field=models.BooleanField(default=False, verbose_name='Chek tasdiqlandi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlash vaqti'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Chekni tasdiqladi'),
        ),
    ]
