# Generated by Django 6.0.1 on 2026-02-12 22:22

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_receipt_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', validators=[apps.core.validators.validate_receipt_file, apps.core.validators.FileSizeValidator(max_size_mb=5)], verbose_name='Chek fayli (PDF)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', validators=[apps.core.validators.FileSizeValidator(max_size_mb=5)], verbose_name='Chek rasmi'),
        ),
    ]
