# Generated by Django 4.2.28 on 2026-02-21 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_add_description_to_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami kirim')),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami chiqim')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Sof summa')),
                ('period_type', models.CharField(choices=[('weekly', 'Haftalik'), ('monthly', 'Oylik')], max_length=20, verbose_name='Davr turi')),
                ('period_start', models.DateField(verbose_name='Davr boshlanishi')),
                ('period_end', models.DateField(verbose_name='Davr tugashi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlash vaqti')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('admin_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_submissions', to='finance.account', verbose_name='Admin kassasi')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqladi')),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_submissions', to='finance.account', verbose_name='Asosiy kassa')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Kassa topshirish',
                'verbose_name_plural': 'Kassa topshirishlar',
                'db_table': 'finance_cash_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
