# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_cash_submission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsubmission',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Naqd pul'),
        ),
        migrations.AddField(
            model_name='cashsubmission',
            name='amount_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Plastik karta'),
        ),
        migrations.AddField(
            model_name='cashsubmission',
            name='amount_terminal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Terminal'),
        ),
        migrations.AddField(
            model_name='cashsubmission',
            name='amount_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Boshqa'),
        ),
    ]