# Generated by Django 6.0.1 on 2026-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_add_payment_method_fields_to_cash_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsubmission',
            name='amount_other',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('terminal', 'Terminal')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
