# Generated by Django 6.0.1 on 2026-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_student_to_supply_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplytransaction',
            name='student',
        ),
        migrations.AddField(
            model_name='cashsubmission',
            name='amount_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Boshqa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('transfer', "Bank o'tkazmasi"), ('online', "Online to'lov")], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
