# Generated by Django 6.0.1 on 2026-03-04 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_supplytransaction_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplytransaction',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_received', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('terminal', 'Terminal')], default='cash', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
