# Generated by Django 6.0.1 on 2026-03-04 21:32

from django.db import migrations


def convert_old_payment_methods(apps, schema_editor):
    """Eski 'transfer' va 'online' qiymatlarni 'terminal' ga o'tkazish."""
    Transaction = apps.get_model('finance', 'Transaction')
    updated = Transaction.objects.filter(
        payment_method__in=['transfer', 'online']
    ).update(payment_method='terminal')
    if updated:
        print(f"  {updated} ta tranzaksiya 'terminal' ga o'tkazildi.")


def reverse_convert(apps, schema_editor):
    """Qaytarish - terminal ni transfer ga."""
    pass  # Qaytarib bo'lmaydi, chunki qaysi biridan kelganini bilmaymiz


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_standardize_payment_methods_and_supply_student'),
    ]

    operations = [
        migrations.RunPython(convert_old_payment_methods, reverse_convert),
    ]
