# Generated by Django 6.0.1 on 2026-03-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_convert_old_payment_methods_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsubmission',
            name='amount_other',
        ),
        migrations.AddField(
            model_name='supplytransaction',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_transactions', to='finance.transaction', verbose_name='Moliyaviy tranzaksiya'),
        ),
        migrations.AddField(
            model_name='supplytransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('terminal', 'Terminal')], max_length=20, null=True, verbose_name="To'lov usuli"),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cash_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.cashsubmission', verbose_name='Kassa topshirish'),
        ),
        migrations.AlterField(
            model_name='cashsubmission',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], max_length=20, verbose_name='Davr turi'),
        ),
    ]
