# Generated by Django 6.0.1 on 2026-03-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_finalize_payment_types_cash_submission_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplytransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarish sanasi'),
        ),
        migrations.AddField(
            model_name='supplytransaction',
            name='is_debt_paid',
            field=models.BooleanField(default=False, verbose_name="Qarz to'landimi?"),
        ),
        migrations.AlterField(
            model_name='supplytransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('terminal', 'Terminal'), ('qarz', 'Qarzga')], max_length=20, null=True, verbose_name="To'lov usuli"),
        ),
    ]
