# Generated by Django 6.0.1 on 2026-03-09 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_supplytransaction_due_date_and_more'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('billing_month', models.DateField(verbose_name='Hisob kitob oyi (Y-M-01)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Yechildimi?')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Qachon yechildi')),
                ('total_students_billed', models.PositiveIntegerField(default=0, verbose_name="Qancha o'quvchidan yechildi")),
                ('total_amount_billed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Umumiy summa')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "Oylik to'lov hisoboti",
                'verbose_name_plural': "Oylik to'lov hisobotlari",
                'db_table': 'finance_monthly_fee_logs',
                'unique_together': {('organization', 'billing_month')},
            },
        ),
    ]
