# Generated by Django 6.0.1 on 2026-03-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_monthlyfeelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', "Kirim (To'lov)"), ('expense', 'Chiqim (Xarajat)'), ('transfer', "O'tkazma"), ('salary', "Oylik to'lov"), ('refund', 'Pul qaytarish'), ('monthly_fee', "Oylik kurs to'lovi (Abonent)")], default='income', max_length=20, verbose_name='Turi'),
        ),
    ]
