# Generated by Django 6.0.1 on 2026-04-14 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_transaction_transaction_type_and_more'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashsubmission',
            index=models.Index(fields=['admin_user', 'status', 'created_at'], name='finance_cas_admin_u_e3a3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsubmission',
            index=models.Index(fields=['organization', 'status', 'period_end'], name='finance_cas_organiz_1ec985_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'status', 'transaction_type'], name='finance_tra_organiz_82a456_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'created_at'], name='finance_tra_organiz_3c8a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['student', 'transaction_type', 'status'], name='finance_tra_student_9d76a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'status', 'cash_submission'], name='finance_tra_account_66384c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'receipt_verified', 'status', 'payment_method'], name='finance_tra_organiz_760fd5_idx'),
        ),
    ]
