# Generated by Django 6.0.1 on 2026-04-15 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_groupstudent_group_stude_student_dc1c81_idx_and_more'),
        ('finance', '0018_cashsubmission_finance_cas_admin_u_e3a3c8_idx_and_more'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('billing_month', models.DateField(verbose_name='Hisob-kitob oyi (Y-M-01)')),
                ('run_type', models.CharField(choices=[('single', "Bitta o'quvchi"), ('bulk', "Barcha o'quvchilar")], max_length=20, verbose_name='Ishga tushirish turi')),
                ('status', models.CharField(choices=[('completed', 'Bajarildi'), ('partial', 'Qisman bajarildi'), ('skipped', 'Yangi yechish topilmadi'), ('failed', 'Xatolik')], default='completed', max_length=20, verbose_name='Holati')),
                ('total_students_processed', models.PositiveIntegerField(default=0, verbose_name="Qamrab olingan o'quvchilar")),
                ('total_charges_created', models.PositiveIntegerField(default=0, verbose_name='Yangi yechilgan kurslar')),
                ('skipped_existing_count', models.PositiveIntegerField(default=0, verbose_name='Oldin yechilgan kurslar')),
                ('total_amount_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami yechilgan summa')),
                ('password_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Parol tasdiqlangan vaqt')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bosilgan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha xulosa")),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('target_student', models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_monthly_fee_runs', to=settings.AUTH_USER_MODEL, verbose_name="Tanlangan o'quvchi")),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_monthly_fee_runs', to=settings.AUTH_USER_MODEL, verbose_name='Kim ishga tushirdi')),
            ],
            options={
                'verbose_name': 'Kurs puli yechish jurnali',
                'verbose_name_plural': 'Kurs puli yechish jurnallari',
                'db_table': 'finance_monthly_fee_runs',
                'ordering': ['-triggered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFeeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('billing_month', models.DateField(verbose_name='Hisob-kitob oyi (Y-M-01)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yechilgan summa')),
                ('charge_source', models.CharField(choices=[('manual_single', "Qo'lda - bitta o'quvchi"), ('manual_bulk', "Qo'lda - barcha o'quvchilar"), ('auto_month_start', 'Avtomatik - oy boshida'), ('auto_mid_month', "Avtomatik - oy o'rtasida")], max_length=30, verbose_name='Manba')),
                ('charged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yechilgan vaqt')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('charged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_monthly_fee_charges', to=settings.AUTH_USER_MODEL, verbose_name='Kim yechdi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fee_charges', to='education.group', verbose_name='Guruh')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fee_charges', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_fee_charges', to='finance.transaction', verbose_name='Yaratilgan tranzaksiya')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='finance.monthlyfeerun', verbose_name='Jarayon logi')),
            ],
            options={
                'verbose_name': 'Kurs puli yechish yozuvi',
                'verbose_name_plural': 'Kurs puli yechish yozuvlari',
                'db_table': 'finance_monthly_fee_charges',
            },
        ),
        migrations.AddIndex(
            model_name='monthlyfeerun',
            index=models.Index(fields=['organization', 'billing_month', 'run_type'], name='finance_mon_organiz_c11e41_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfeerun',
            index=models.Index(fields=['triggered_by', 'triggered_at'], name='finance_mon_trigger_959305_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfeerun',
            index=models.Index(fields=['status', 'triggered_at'], name='finance_mon_status_3ecbb4_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfeecharge',
            index=models.Index(fields=['organization', 'billing_month'], name='finance_mon_organiz_d2c7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfeecharge',
            index=models.Index(fields=['student', 'billing_month'], name='finance_mon_student_501305_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyfeecharge',
            index=models.Index(fields=['run', 'charged_at'], name='finance_mon_run_id_94e9f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfeecharge',
            unique_together={('organization', 'billing_month', 'student', 'group')},
        ),
    ]
