# Generated by Django 6.0.1 on 2026-01-18 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Yaratildi'), ('UPDATE', "O'zgartirildi"), ('DELETE', "O'chirildi"), ('LOGIN', 'Tizimga kirdi'), ('LOGOUT', 'Tizimdan chiqdi')], max_length=20, verbose_name='Amal')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nomi')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Obyekt nomi')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name="O'zgarishlar")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Manzil')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='Brauzer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kim bajardi')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Loglar',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
