# Generated by Django 6.0.1 on 2026-04-15

import uuid
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('name', models.CharField(default='Asosiy backup sozlamasi', max_length=100, verbose_name='Nomi')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Avtomatik backup yoqilgan')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Telegram bot token')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram chat ID')),
                ('auto_detect_chat', models.BooleanField(default=True, verbose_name='Chat ID ni avtomatik topish')),
                ('schedule_type', models.CharField(choices=[('manual', "Faqat qo'lda"), ('interval', 'Har N soatda'), ('daily', 'Har kuni aniq vaqtda')], default='manual', max_length=20, verbose_name='Backup rejimi')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Interval (soat)')),
                ('daily_time', models.TimeField(blank=True, null=True, verbose_name='Kunlik backup vaqti')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='Backup saqlash kunlari')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi ishga tushgan vaqt')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Keyingi backup vaqti')),
                ('last_status', models.CharField(choices=[('never', 'Hali ishga tushmagan'), ('success', 'Muvaffaqiyatli'), ('failed', 'Xatolik bilan tugagan')], default='never', max_length=20, verbose_name='Oxirgi holat')),
                ('last_message', models.TextField(blank=True, verbose_name='Oxirgi xabar')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_config_updates', to=settings.AUTH_USER_MODEL, verbose_name='Kim yangiladi')),
            ],
            options={
                'verbose_name': 'Backup sozlamasi',
                'verbose_name_plural': 'Backup sozlamalari',
                'db_table': 'backup_configurations',
            },
        ),
        migrations.CreateModel(
            name='BackupRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('trigger_source', models.CharField(choices=[('manual', "Qo'lda"), ('schedule', 'Jadval bo`yicha')], default='manual', max_length=20, verbose_name='Ishga tushish turi')),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Xatolik')], max_length=20, verbose_name='Holati')),
                ('backup_file_name', models.CharField(blank=True, max_length=255, verbose_name='Backup fayl nomi')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Fayl hajmi')),
                ('sent_to_telegram', models.BooleanField(default=False, verbose_name='Telegramga yuborildimi')),
                ('message', models.TextField(blank=True, verbose_name='Natija xabari')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_logs', to='core.backupconfiguration', verbose_name='Sozlama')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to=settings.AUTH_USER_MODEL, verbose_name='Kim ishga tushirdi')),
            ],
            options={
                'verbose_name': 'Backup log',
                'verbose_name_plural': 'Backup loglari',
                'db_table': 'backup_run_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
