# Generated by Django 6.0.1 on 2026-01-13 22:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('owner', 'Direktor'), ('admin', 'Administrator'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('parent', 'Ota-ona'), ('staff', 'Xodim')], default='student', max_length=20, verbose_name='Roli')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Rasm')),
                ('nfc_card_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NFC ID (Turniket)')),
                ('profile_data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha Info")),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Hisob (Balans)')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.branch', verbose_name='Filial')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ParentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relation_type', models.CharField(choices=[('father', 'Otasi'), ('mother', 'Onasi'), ('guardian', 'Vasiysi'), ('relative', 'Qarindoshi')], default='mother', max_length=20, verbose_name='Qarindoshligi')),
                ('is_main_contact', models.BooleanField(default=False, verbose_name='Asosiy aloqa uchunmi?')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ota-ona bog'liqligi",
                'verbose_name_plural': "Ota-ona bog'liqliklari",
                'db_table': 'parent_student_relations',
                'unique_together': {('parent', 'student')},
            },
        ),
    ]
