# Generated by Django 6.0.1 on 2026-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_users_organiz_6045b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ruxsatlar'),
        ),
    ]
