# Generated by Django 6.0.2 on 2026-02-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_permissions_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_export_users_excel', "Foydalanuvchilar ro'yxatini Excel eksport qilish"), ('can_export_users_pdf', "Foydalanuvchilar ro'yxatini PDF eksport qilish"), ('can_view_salary', "Xodim oyligini ko'rish"), ('can_export_finance_excel', 'Moliya hisobotini Excel eksport qilish'), ('can_export_crm_excel', "CRM ma'lumotlarini Excel eksport qilish"), ('can_export_reports_excel', 'Hisobotlarni Excel eksport qilish'), ('can_export_reports_pdf', 'Hisobotlarni PDF eksport qilish')], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
