# Generated by Django 6.0.1 on 2026-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_custom_granular_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp_total',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Jami XP Ballari'),
        ),
    ]
