# Generated by Django 6.0.1 on 2026-03-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_xp_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='xp_total',
        ),
    ]
