# Generated by Django 6.0.1 on 2026-03-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_xp_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tasdiqlangan Bonus summasi'),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Bonus foizi (%)'),
        ),
    ]
