# Generated by Django 6.0.1 on 2026-01-13 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('call', "Qo'ng'iroq"), ('sms', 'SMS'), ('meeting', 'Uchrashuv'), ('note', 'Izoh'), ('status_change', "Status o'zgardi")], default='note', max_length=20)),
                ('comment', models.TextField(verbose_name='Izoh/Natija')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Harakatlar',
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha Info")),
            ],
            options={
                'verbose_name': 'Lid',
                'verbose_name_plural': 'Lidlar',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Manba nomi')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Kodo')),
            ],
            options={
                'verbose_name': 'Lid Manbasi',
                'verbose_name_plural': 'Lid Manbalari',
                'db_table': 'lead_sources',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Bosqich nomi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ketma-ketlik')),
                ('color', models.CharField(default='#3B82F6', max_length=20, verbose_name='Rangi (HEX)')),
                ('is_won', models.BooleanField(default=False, verbose_name='Yutuq bosqichimi?')),
            ],
            options={
                'verbose_name': 'Voronka Bosqichi',
                'verbose_name_plural': 'Voronka Bosqichlari',
                'db_table': 'crm_stages',
                'ordering': ['order'],
            },
        ),
    ]
