# Generated by Django 6.0.1 on 2026-01-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_initial'),
        ('education', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bajardi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'owner', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim"),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.course', verbose_name='Qiziqqan kursi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.leadsource', verbose_name='Manba'),
        ),
        migrations.AddField(
            model_name='stage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='crm.stage', verbose_name='Bosqich'),
        ),
    ]
