# Generated by Django 6.0.1 on 2026-02-14 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_initial'),
        ('education', '0004_add_materials_lms'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name="To'liq ismi"),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'stage'], name='leads_organiz_a949a0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_created_e6e479_idx'),
        ),
    ]
