# Generated by Django 6.0.1 on 2026-01-13 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Bor'), ('absent', "Yo'q (Sababsiz)"), ('excused', 'Sababli'), ('late', 'Kechikdi')], default='present', max_length=10)),
                ('grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baho (0-100)')),
                ('xp_points', models.PositiveIntegerField(default=0, verbose_name='XP Ochko')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Mavzu')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('started', 'Dars ketmoqda'), ('finished', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='scheduled', max_length=20, verbose_name='Holati')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'db_table': 'lessons',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
