# Generated by Django 6.0.1 on 2026-01-18 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_add_receipt_verification'),
        ('operations', '0004_badge_lessongenerationlog_level_schedulepattern_and_more'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(default='🎁', max_length=50, verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "Do'kon kategoriyasi",
                'verbose_name_plural': "Do'kon kategoriyalari",
                'db_table': 'shop_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('coin_price', models.PositiveIntegerField(default=100, verbose_name='Coin narxi')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Mavjud soni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/%Y/%m/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='operations.shopcategory', verbose_name='Kategoriya')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_items', to='finance.supply', verbose_name='Sklad mahsuloti')),
            ],
            options={
                'verbose_name': "Do'kon mahsuloti",
                'verbose_name_plural': "Do'kon mahsulotlari",
                'db_table': 'shop_items',
                'ordering': ['-is_featured', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('coin_spent', models.PositiveIntegerField(verbose_name='Sarflangan coin')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('delivered', 'Topshirildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Topshirilgan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Topshirdi')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='operations.shopitem', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Xarid',
                'verbose_name_plural': 'Xaridlar',
                'db_table': 'shop_purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
