# Generated by Django 6.0.1 on 2026-01-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_add_shop_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan summa"),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(choices=[('coin', 'Coin bilan'), ('cash', 'Pul bilan')], default='coin', max_length=10, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/receipts/%Y/%m/', verbose_name='Chek rasmi'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_verified',
            field=models.BooleanField(default=False, verbose_name='Chek tasdiqlandi'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='allow_cash_purchase',
            field=models.BooleanField(default=True, verbose_name='Pul bilan olish'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='allow_coin_purchase',
            field=models.BooleanField(default=True, verbose_name='Coin bilan olish'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='cash_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Pul narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='shop/digital/%Y/%m/', verbose_name='Elektron fayl (PDF)'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='digital_link',
            field=models.URLField(blank=True, verbose_name='Tashqi havola'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='item_type',
            field=models.CharField(choices=[('physical', 'Jismoniy mahsulot'), ('digital', 'Elektron mahsulot'), ('book_physical', "Kitob (Qog'oz)"), ('book_digital', 'Kitob (Elektron)'), ('voucher', 'Chegirma kuponi'), ('service', 'Xizmat')], default='physical', max_length=20, verbose_name='Mahsulot turi'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='coin_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Sarflangan coin'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan (tasdiq kutilmoqda)"), ('delivered', 'Topshirildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='coin_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Coin narxi'),
        ),
    ]
