# Generated by Django 6.0.1 on 2026-02-16 11:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_teacher_lesson_rating'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWeeklyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField(verbose_name='Hafta boshlanishi')),
                ('week_end', models.DateField(verbose_name='Hafta tugashi')),
                ('preparation', models.PositiveSmallIntegerField(default=5, verbose_name='Tayyorgarlik')),
                ('delivery', models.PositiveSmallIntegerField(default=5, verbose_name='Tushuntirish')),
                ('engagement', models.PositiveSmallIntegerField(default=5, verbose_name='Faollik')),
                ('punctuality', models.PositiveSmallIntegerField(default=5, verbose_name='Vaqtga rioya')),
                ('overall', models.PositiveSmallIntegerField(default=5, verbose_name='Umumiy baho')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_teacher_ratings', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi haftalik bahosi",
                'verbose_name_plural': "O'qituvchi haftalik baholari",
                'db_table': 'teacher_weekly_ratings',
                'ordering': ['-week_start'],
                'unique_together': {('teacher', 'week_start')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherLessonRating',
        ),
    ]
