# Generated by Django 6.0.1 on 2026-04-14 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_groupstudent_group_stude_student_dc1c81_idx_and_more'),
        ('operations', '0008_teacher_weekly_rating'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['organization', 'date'], name='lessons_organiz_d8b0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date'], name='lessons_teacher_13c796_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['group', 'date'], name='lessons_group_i_1e5b73_idx'),
        ),
    ]
