# Generated by Django 6.0.1 on 2026-01-13 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi (Oylik)')),
                ('duration_months', models.PositiveIntegerField(default=3, verbose_name='Davomiyligi (oy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('status', models.CharField(choices=[('pending', "Yig'ilmoqda"), ('active', 'Dars ketmoqda'), ('finished', 'Tugatilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('schedule_days', models.JSONField(default=list, verbose_name='Dars kunlari (1=Dush...7=Yak)')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('status', models.CharField(choices=[('active', "O'qiyapti"), ('frozen', 'Muzlatilgan'), ('left', 'Chiqib ketgan')], default='active', max_length=20, verbose_name='Status')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': "Guruh a'zosi",
                'verbose_name_plural': "Guruh a'zolari",
                'db_table': 'group_students',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Xona nomi')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name="Sig'imi")),
                ('has_projector', models.BooleanField(default=False, verbose_name='Proyektor bormi?')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'db_table': 'rooms',
            },
        ),
    ]
