# Generated by Django 6.0.1 on 2026-01-18 18:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_initial'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('icon', models.CharField(default='📁', max_length=50, verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Material kategoriyasi',
                'verbose_name_plural': 'Material kategoriyalari',
                'db_table': 'material_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('material_type', models.CharField(choices=[('video', '🎬 Video'), ('pdf', '📄 PDF'), ('audio', '🎧 Audio'), ('doc', '📝 Hujjat'), ('link', '🔗 Havola'), ('other', '📦 Boshqa')], default='pdf', max_length=20, verbose_name='Turi')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='Fayl')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Tashqi havola')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='materials/thumbnails/', verbose_name='Muqova rasmi')),
                ('access_type', models.CharField(choices=[('all', 'Hamma uchun'), ('group', "Faqat guruh a'zolari"), ('private', "Tanlangan o'quvchilar")], default='all', max_length=20, verbose_name='Kirish huquqi')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilgan')),
                ('allowed_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='private_materials', to=settings.AUTH_USER_MODEL, verbose_name="Ruxsat berilgan o'quvchilar")),
                ('groups', models.ManyToManyField(blank=True, related_name='materials', to='education.group', verbose_name='Guruhlar')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Yukladi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='education.materialcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.PositiveIntegerField(default=0, verbose_name="Ko'rish davomiyligi (soniya)")),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='education.material')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Material ko'rish",
                'verbose_name_plural': "Material ko'rishlar",
                'db_table': 'material_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Reja nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabi/%Y/', verbose_name='Reja fayli')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_syllabi', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='education.group', verbose_name='Guruh')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "O'quv rejasi",
                'verbose_name_plural': "O'quv rejalari",
                'db_table': 'syllabi',
            },
        ),
        migrations.CreateModel(
            name='SyllabusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='Davomiylik (soat)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Yakunlandi')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Yakunlangan sana')),
                ('materials', models.ManyToManyField(blank=True, related_name='syllabus_items', to='education.material', verbose_name='Materiallar')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='education.syllabus')),
            ],
            options={
                'verbose_name': "O'quv rejasi bandi",
                'verbose_name_plural': "O'quv rejasi bandlari",
                'db_table': 'syllabus_items',
                'ordering': ['syllabus', 'order'],
            },
        ),
    ]
