# Generated by Django 6.0.1 on 2026-04-14 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_add_materials_lms'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupstudent',
            index=models.Index(fields=['student', 'status'], name='group_stude_student_dc1c81_idx'),
        ),
        migrations.AddIndex(
            model_name='groupstudent',
            index=models.Index(fields=['group', 'status'], name='group_stude_group_i_e7a01b_idx'),
        ),
    ]
