# Generated by Django 6.0.1 on 2026-04-14 18:41

import apps.hardware.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIDIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('agent_enabled', models.BooleanField(default=False, verbose_name='Agent yoqilgan')),
                ('device_token', models.CharField(default=apps.hardware.models.generate_device_token, max_length=64, unique=True, verbose_name='Qurilma tokeni')),
                ('last_event_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi event vaqti')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_id_integration', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Face ID integratsiya',
                'verbose_name_plural': 'Face ID integratsiyalar',
                'db_table': 'hardware_face_id_integrations',
            },
        ),
        migrations.CreateModel(
            name='FaceIDEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('face_id_code', models.CharField(max_length=64, verbose_name='Face ID kodi')),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Keldi'), ('CHECK_OUT', 'Ketdi')], max_length=20, verbose_name='Event turi')),
                ('occurred_at', models.DateTimeField(verbose_name="Qachon bo'lgan")),
                ('device_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Qurilma IP')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Xom payload')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_id_events', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Face ID event',
                'verbose_name_plural': 'Face ID eventlar',
                'db_table': 'hardware_face_id_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', 'occurred_at'], name='hardware_fa_organiz_9b6d7a_idx'), models.Index(fields=['organization', 'face_id_code', 'occurred_at'], name='hardware_fa_organiz_ff0237_idx')],
                'unique_together': {('organization', 'face_id_code', 'event_type', 'occurred_at')},
            },
        ),
        migrations.CreateModel(
            name='FaceIDUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('face_id_code', models.CharField(max_length=64, verbose_name='Face ID kodi')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync yoqilgan')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi sync')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi event')),
                ('last_event_type', models.CharField(blank=True, max_length=20, verbose_name='Oxirgi event turi')),
                ('last_device_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Oxirgi qurilma IP')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='organizations.organization', verbose_name='Tashkilot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_id_binding', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Face ID bog'lanish",
                'verbose_name_plural': "Face ID bog'lanishlar",
                'db_table': 'hardware_face_id_bindings',
                'indexes': [models.Index(fields=['organization', 'sync_enabled'], name='hardware_fa_organiz_3444fa_idx'), models.Index(fields=['organization', 'face_id_code'], name='hardware_fa_organiz_8ef78b_idx')],
                'unique_together': {('organization', 'face_id_code')},
            },
        ),
    ]
