# Generated by Django 6.0.1 on 2026-01-13 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Filial nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Filial Sozlamalari')),
                ('is_main', models.BooleanField(default=False, verbose_name='Bosh filialmi?')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilganmi?")),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Markaz nomi')),
                ('subdomain', models.CharField(max_length=50, unique=True, verbose_name='Subdomain')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Tizim Sozlamalari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'db_table': 'organizations',
            },
        ),
    ]
